### ISSUE TITLE
Fribourg should be Fribourg in english

### ISSUE THREAD

**Issue by jminguely** [stefanzweifel/php-swiss-cantons#23]
Thanks for your work!

There is a small typo for the Canton Fribourg, in english.

https://github.com/stefanzweifel/php-swiss-cantons/blob/abda04ac6d4bf9394478eb92208a06247b763a3a/src/data/cantons.json#L69

**Comment by stefanzweifel** [comment]
Thanks. I've fixed it in ea8b44e9ba1808cc26bb3cb9688d6dd18b01b786 and tagged a new release (2.0.1)
