### ISSUE TITLE
Zipcodes 8060 and 7001 not found in data files

### ISSUE THREAD

**Issue by adrian-gheorghe** [stefanzweifel/php-swiss-cantons#37]
Found that the following zipcodes are not in the data files:

> 8060 - Should be Zürich
> 7001 - City of Chur

Thanks for this great extension

**Comment by stefanzweifel** [comment]
Thanks for reporting!
Will update the data set in the next couple of days with the dataset of the Swiss Post. (https://swisspost.opendatasoft.com/explore/dataset/plz_verzeichnis_v2/table/?q=8060).

**Comment by adrian-gheorghe** [comment]
That's amazing. I'll be looking forward to that release and will be using it in our project. Thank you!

**Comment by stefanzweifel** [comment]
@adrian-gheorghe The data set has just been updated. Both 8060 and 7001 are now included.

In #38 a new console command has been added to automate the update process in the future.
I've tagged a new major version (v4.0.0) as the dataset source changed. The public API of the package remains the same.

**Comment by adrian-gheorghe** [comment]
Thank you @stefanzweifel !
