### ISSUE TITLE
Allow search by zip code

### ISSUE THREAD

**Issue by wittwerch** [stefanzweifel/php-swiss-cantons#4]
It would be helpful if a canton could also be found by zip code.

```
$canton = $cantonManager->getByZipCode(8001);
```

**Comment by stefanzweifel** [comment]
Great idea, but then the package would have to ship with a complete "Database" containing all Swiss Zipcodes (there are currently 4250 zipcodes).

Or we could try to use [this pattern](https://de.wikipedia.org/wiki/Postleitzahl_%28Schweiz%29#Schweiz).

**Comment by wittwerch** [comment]
I think it's not possible to avoid storing a mapping table in the package, because there is no pattern in it.

Please have a look at that dataset: http://www.bfs.admin.ch/bfs/portal/de/index/infothek/nomenklaturen/blank/blank/gem_liste/04.html

Example from the dataset
![image](https://cloud.githubusercontent.com/assets/1575445/18506249/663f875a-7a6b-11e6-9e2d-77d1efa1a0d0.png)

1290 => GE
1291 => VD
1292 => GE

**Comment by stefanzweifel** [comment]
Thanks for the link. I will see what I can do. If you have already an idea, on how to implement this: PRs are always welcome :)

**Comment by stefanzweifel** [comment]
Just a quick follow-up question: Can you describe in which scenario / context you're going to use this feature?

**Comment by wittwerch** [comment]
I want to auto-complete the profile of a user. The user has to do a registration and I want to keep it simple. Canton is something that I can "compute", so I don't want to ask the user for it.

**Comment by stefanzweifel** [comment]
I just merged my PR and tagged a new [release](https://github.com/stefanzweifel/php-swiss-cantons/releases/tag/1.1.0).
